version: 2
jobs:
  build:
    # 対象のブランチ
    # master に限定
    branches:
      only:
        - master
　　　　# 使用する Docker イメージ
　　　　# Rails 用の Ruby イメージ
　　　　# MySQL 用のイメージ
    docker:
       - image: circleci/ruby:2.5.3-node-browsers
         # MySQL に接続するための環境変数を設定
         # テスト用なのでデフォルトのまま（rootユーザー）
         environment:
           RAILS_ENV: test
           DB_USERNAME: 'root'
           DB_PASSWORD: 'password'

       - image: circleci/mysql:5.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # テストデータベースの設定
      - run: rm ./config/database.yml
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:migrate RAILS_ENV=test

      # テスト実行
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --out /tmp/test-results/rspec.xml \
                            $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
